"""Class definition of GraphState"""

from typing import List

from typing_extensions import TypedDict


class GraphState(TypedDict):
    """Represents the state of the grpah.
    Attributes:
        question: The question - input to the graph
        generation: The answer generated by LLM
        web_search: Whether to invoke web search
        documents: The list of documents
    """

    question: str
    generation: str
    web_search: str
    documents: List[str]
